# Generated by Django 3.1 on 2020-08-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hoja',
            fields=[
                ('idhoja', models.IntegerField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=20)),
                ('Fecha', models.DateTimeField(auto_now_add=True)),
                ('Ideas', models.CharField(max_length=600)),
                ('Tema', models.CharField(max_length=700)),
                ('Resumen', models.CharField(max_length=600)),
            ],
        ),
    ]
